export enum pwdDocx {
  main = "ОБ ИНСТИТУТЕ",
  THESTUDENTSCOUNCIL = "УЧЕНЫЙ СОВЕТ",
  BOOKLET = "БУКЛЕТ",
  REFERENCE = "ОБРАТНАЯ СВЯЗЬ",
  CURRENTTIPS = "ДЕЙСТВУЮЩИЕ СОВЕТЫ",
  ARCHIVE = "АРХИВ",
  DEPARTMENTOFNUMBERTHEORYALGEBRAANDTOPOLOGY = "ОТДЕЛ ТЕОРИИ ЧИСЕЛ,АЛГЕБРЫ И ТОПОЛОГИИ",
  DIFFERENTIALEQUATIONSDEPARTMENT = "ОТДЕЛ ДИФФЕРЕНЦИАЛЬНЫХ УРАВНЕНИЙ",
  DEPARTMENTOFFUNCTIONTHEORYANDFUNCTIONALANALYSIS = "ОТДЕЛ ТЕОРИЯ ФУНКЦИЙ И ФУНКЦИОНАЛЬНОГО АНАЛИЗА",
  DEPARTMENTOFAPPLIEDMATHEMATICSANDMECHANICS = "ОТДЕЛ ПРИКЛАДНОЙ МАТЕМАТИКИ И МЕХАНИКИ",
  DEPARTMENTOFMATHEMATICALMODELING = "ОТДЕЛ МАТЕМАТИЧЕСКОГО МОДЕЛИРОВАНИЯ",
  COLLEGESEMINAR = "ОБЩЕИНСТИТУТСКИЙ СЕМИНАР",
  CONSTRUCTORS = "СОТРУДНИКИ",
  SEMINARSOFTHERUSSIANACADEMYOFSCIENCES = "СЕМИНАРЫ ИМ АН РТ",
  NEWS = "НОВОСТИ",
  CONFERENCEPROCEEDINGS = "МАТЕРИАЛЫ КОНФЕРЕНЦИЙ",
  REPORTSOFTHEACADEMYOFSCIENCESOFTHEREPUBLICOFTATARSTAN = "ДОКЛАДЫ АН РТ",
  IZVESTIAOFTHEACADEMYOFSCIENCESOFTHEREPUBLICOFTATARSTAN = "ИЗВЕСТИЯ АН РТ",
}
