export enum RegUserAT {
  HANDLE_SUBMIT = "HANDLE_SUBMIT",
  HANLDE_SUCCESS = "HANLDE_SUCCESS",
  HANDLE_CHANGE = "HANLDE_CHANGE",
}

export enum GetUserAT {
  GETUSER_SUCCESS = "GETUSER_SUCCESS",
}

export enum GetAllDocxAT {
  GETDOCX_SUCCESS = "GETDOCX_SUCCESS",
  GETDOCX_FAILED = "GETDOCX_FAILED",
  GETDOCX_LOADING = "GETDOCX_LOADING",
}
