import { JsxChild } from "typescript";

export interface routs {
  path: string;
  layout: JsxChild;
}

export enum urls {
  main = "/main",
  regUsers = "/regiserUser",
  booklet = "/booklet",
  loginAdmin = "/loginadmin",
  seminar = "/iwideseminar",
  admin = "/admin",
  COLLEGESEMINAR = "/COLLEGESEMINAR",
  THESTUDENTSCOUNCIL = "/THESTUDENTSCOUNCIL",
  REFERENCE = "/REFERENCE",
  CURRENTTIPS = "/CURRENTTIPS",
  ARCHIVE = "/ARCHIVE",
  DEPARTMENTOFNUMBERTHEORYALGEBRAANDTOPOLOGY = "/DEPARTMENTOFNUMBERTHEORYALGEBRAANDTOPOLOGY",
  DIFFERENTIALEQUATIONSDEPARTMENT = "/DIFFERENTIALEQUATIONSDEPARTMENT",
  DEPARTMENTOFFUNCTIONTHEORYANDFUNCTIONALANALYSIS = "/DEPARTMENTOFFUNCTIONTHEORYANDFUNCTIONALANALYSIS",
  DEPARTMENTOFAPPLIEDMATHEMATICSANDMECHANICS = "/DEPARTMENTOFAPPLIEDMATHEMATICSANDMECHANICS",
  DEPARTMENTOFMATHEMATICALMODELING = "/DEPARTMENTOFMATHEMATICALMODELING",
  CONSTRUCTORS = "/CONSTRUCTORS",
  SEMINARSOFTHERUSSIANACADEMYOFSCIENCES = "/SEMINARSOFTHERUSSIANACADEMYOFSCIENCES",
  NEWS = "/NEWS",
  CONFERENCEPROCEEDINGS = "/CONFERENCEPROCEEDINGS",
  REPORTSOFTHEACADEMYOFSCIENCESOFTHEREPUBLICOFTATARSTAN = "/REPORTSOFTHEACADEMYOFSCIENCESOFTHEREPUBLICOFTATARSTAN",
  IZVESTIAOFTHEACADEMYOFSCIENCESOFTHEREPUBLICOFTATARSTAN = "/IZVESTIAOFTHEACADEMYOFSCIENCESOFTHEREPUBLICOFTATARSTAN",
}
